version: '3.4'

services:
  contents-vis-server:
    image: contents-vis-server
    build: .
    extra_hosts:
      - "localhost:192.168.11.11" #should be locap ip for elasticsearch
    ports:
      - "5000:5000"
    env_file:
      - local.env