version: '3.4'

services:
  contents-vis-server:
    image: contents-vis-server
    build: .
    extra_hosts:
      - "localhost:192.168.11.101"
    ports:
      - "5000:5000"
    # environment:
    #   API_HOST: "192.168.11.101" 